// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AuthStatus(arg1) {
  return window['go']['main']['App']['AuthStatus'](arg1);
}

export function CLIInfo() {
  return window['go']['main']['App']['CLIInfo']();
}

export function CancelLogin(arg1) {
  return window['go']['main']['App']['CancelLogin'](arg1);
}

export function ConfirmSpecCommit(arg1, arg2) {
  return window['go']['main']['App']['ConfirmSpecCommit'](arg1, arg2);
}

export function EndSession(arg1) {
  return window['go']['main']['App']['EndSession'](arg1);
}

export function GateDecide(arg1, arg2, arg3) {
  return window['go']['main']['App']['GateDecide'](arg1, arg2, arg3);
}

export function GateList() {
  return window['go']['main']['App']['GateList']();
}

export function ListWorkspace(arg1) {
  return window['go']['main']['App']['ListWorkspace'](arg1);
}

export function Logout(arg1) {
  return window['go']['main']['App']['Logout'](arg1);
}

export function NewSession(arg1) {
  return window['go']['main']['App']['NewSession'](arg1);
}

export function PreviewSpecCommit() {
  return window['go']['main']['App']['PreviewSpecCommit']();
}

export function ReadDiagram() {
  return window['go']['main']['App']['ReadDiagram']();
}

export function ReadWorkspaceFile(arg1) {
  return window['go']['main']['App']['ReadWorkspaceFile'](arg1);
}

export function ResolveApproval(arg1, arg2, arg3) {
  return window['go']['main']['App']['ResolveApproval'](arg1, arg2, arg3);
}

export function RestartCodexServerRecorded(arg1) {
  return window['go']['main']['App']['RestartCodexServerRecorded'](arg1);
}

export function RestoreViews() {
  return window['go']['main']['App']['RestoreViews']();
}

export function SendMessage(arg1, arg2) {
  return window['go']['main']['App']['SendMessage'](arg1, arg2);
}

export function SpecAssist(arg1, arg2, arg3) {
  return window['go']['main']['App']['SpecAssist'](arg1, arg2, arg3);
}

export function SpecList() {
  return window['go']['main']['App']['SpecList']();
}

export function SpecRead(arg1) {
  return window['go']['main']['App']['SpecRead'](arg1);
}

export function SpecWrite(arg1, arg2, arg3) {
  return window['go']['main']['App']['SpecWrite'](arg1, arg2, arg3);
}

export function StartLogin(arg1) {
  return window['go']['main']['App']['StartLogin'](arg1);
}

export function StartSession(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['StartSession'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function SubmitForApproval() {
  return window['go']['main']['App']['SubmitForApproval']();
}

export function TerminateSession(arg1) {
  return window['go']['main']['App']['TerminateSession'](arg1);
}
