// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AuthStatus(arg1:string):Promise<string>;

export function CLIInfo():Promise<Record<string, string>>;

export function CancelLogin(arg1:string):Promise<void>;

export function EndSession(arg1:string):Promise<void>;

export function ListWorkspace(arg1:string):Promise<Array<main.FileNode>>;

export function Logout(arg1:string):Promise<void>;

export function ReadDiagram():Promise<string>;

export function ReadWorkspaceFile(arg1:string):Promise<string>;

export function ResolveApproval(arg1:string,arg2:boolean,arg3:string):Promise<void>;

export function RestartCodexServerRecorded(arg1:string):Promise<void>;

export function SendMessage(arg1:string,arg2:string):Promise<void>;

export function StartLogin(arg1:string):Promise<void>;

export function StartSession(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string):Promise<void>;

export function TerminateSession(arg1:string):Promise<void>;
