// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {contract} from '../models';
import {spec} from '../models';
import {escalation} from '../models';
import {evidence} from '../models';
import {gate} from '../models';

export function AuthStatus(arg1:string):Promise<string>;

export function CLIInfo():Promise<Record<string, string>>;

export function CancelLogin(arg1:string):Promise<void>;

export function ConfirmAnalysisBaseBump(arg1:main.BumpToken,arg2:string,arg3:string):Promise<string>;

export function ConfirmPlanCommit(arg1:spec.CommitToken,arg2:string):Promise<void>;

export function ConfirmSpecCommit(arg1:spec.CommitToken,arg2:string):Promise<void>;

export function CreateSession(arg1:string,arg2:string):Promise<string>;

export function EndSession(arg1:string):Promise<void>;

export function EscalationAck(arg1:string):Promise<void>;

export function EscalationCreate(arg1:string,arg2:string,arg3:string):Promise<string>;

export function EscalationList():Promise<Array<escalation.Entry>>;

export function EscalationResolve(arg1:string,arg2:string,arg3:string):Promise<void>;

export function EvidenceCommitCandidates(arg1:string):Promise<Array<main.CommitInfo>>;

export function EvidenceGet(arg1:string):Promise<evidence.EvidenceRun>;

export function GateDecide(arg1:string,arg2:string,arg3:string,arg4:Array<gate.RiskSelection>):Promise<void>;

export function GateDecisionContext(arg1:string):Promise<main.GateDecisionContextDTO>;

export function GateList():Promise<Array<main.GateEntryDTO>>;

export function ListWorkspace(arg1:string):Promise<Array<main.FileNode>>;

export function LoadTurnsBefore(arg1:string,arg2:string,arg3:number):Promise<Array<contract.Envelope>>;

export function Logout(arg1:string):Promise<void>;

export function NewSession(arg1:string):Promise<void>;

export function PlanAssist(arg1:string,arg2:string):Promise<string>;

export function PlanList():Promise<Array<main.FileNode>>;

export function PlanRead(arg1:string):Promise<main.SpecFile>;

export function PlanWrite(arg1:string,arg2:string,arg3:string):Promise<string>;

export function PreviewAnalysisBaseBump(arg1:string,arg2:string):Promise<main.BumpPreview>;

export function PreviewPlanCommit():Promise<main.SpecCommitPreview>;

export function PreviewSpecCommit():Promise<main.SpecCommitPreview>;

export function ReadDiagram():Promise<string>;

export function ReadWorkspaceFile(arg1:string):Promise<string>;

export function RecoverCodexRecording():Promise<void>;

export function RegisterMutation(arg1:string,arg2:string):Promise<string>;

export function ResolveApproval(arg1:string,arg2:boolean,arg3:string):Promise<void>;

export function RestartCodexServerRecorded(arg1:string):Promise<void>;

export function RestoreViews():Promise<Record<string, main.RestoredView>>;

export function RunEvidence(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string):Promise<string>;

export function SendMessage(arg1:string,arg2:string):Promise<void>;

export function SpecAssist(arg1:string,arg2:string,arg3:string):Promise<string>;

export function SpecList():Promise<Array<main.FileNode>>;

export function SpecRead(arg1:string):Promise<main.SpecFile>;

export function SpecWrite(arg1:string,arg2:string,arg3:string):Promise<string>;

export function StartLogin(arg1:string):Promise<void>;

export function StartSession(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string):Promise<void>;

export function SubmitForApproval():Promise<string>;

export function SubmitPlanForApproval(arg1:string):Promise<string>;

export function SubmitTestContract(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string):Promise<string>;

export function TerminateSession(arg1:string):Promise<void>;

export function ValidateTestCommit(arg1:string,arg2:string,arg3:string):Promise<void>;
