// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AuthStatus(arg1) {
  return window['go']['main']['App']['AuthStatus'](arg1);
}

export function CLIInfo() {
  return window['go']['main']['App']['CLIInfo']();
}

export function Logout(arg1) {
  return window['go']['main']['App']['Logout'](arg1);
}

export function ReadDiagram() {
  return window['go']['main']['App']['ReadDiagram']();
}

export function ResolveApproval(arg1, arg2, arg3) {
  return window['go']['main']['App']['ResolveApproval'](arg1, arg2, arg3);
}

export function RestartCodexServerRecorded(arg1) {
  return window['go']['main']['App']['RestartCodexServerRecorded'](arg1);
}

export function StartLogin(arg1) {
  return window['go']['main']['App']['StartLogin'](arg1);
}

export function StartSession(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['StartSession'](arg1, arg2, arg3, arg4);
}

export function TerminateSession() {
  return window['go']['main']['App']['TerminateSession']();
}
